lista = [i for i in range(25) for _ in range(5)]

print(lista)

print(len(lista))

# Diccionario de pigmentos  y sus etiquetas
pigmentos = {
    'C1': {
        0: "Ocre de mina inglés. Kremer",
        1: "Oropimente",
        2: "Amarillo de plomo estaño. Tipo II. Kremer",
        3: "Ancorca. Sennelier",
        4: "Ancorca o gualda. Zeechi",
    },
    'C2': {
        5: "Ocre claro. Kremer",
        6: "Sombra tostada de Chipre. Kremer",
        7: "Ocre oscuro Siena. Kremer 40310",
        8: "Siena tostada. Kremer 40430",
        9: "Betún de Judea. Sennelier",
    },
    'C3': {
        10: "Cinabrio.Kremer",
        11: "Almagre",
        12: "Azarcón o minio",
        13: "Carmín de cochinilla",
        14: "Laca de alizarina",
    },
    'C4': {
        15: "Rejalgar",
        16: "Azurita",
        17: "Esmalte",
        18: "Lapislázuli",
        19: "Índigo o añil",
    },
    'C5': {
        20: "Acetato básico de cobre. Verdigris",
        21: "Malaquita africana",
        22: "Tierra verde de Verona",
        23: "Negro de huesos",
        24: "Negro de humo",
    },
    'C6': {
        25: "Bermellon",
        26: "Cochinilla",
        27: "Azurita",
        28: "Amarillo de plomo estaño. Lead Tin Yellow Deep. Kremer",
        29: "Blanco de plomo. Kremer",
    },
    'C7': {
        31: "Rejalgar",
        33: "Gualda",
        34: "Arzica",
        35: "Pardo antílope",
        36: "Sombra tostada",
        37: "Ocre oscuro",
        41: "Almagre",
        42: "Minio",
        43: "Laca carmín",
        44: "Carmín de alizarina",
        45: "Laca rubia",
        46: "Azurita natural. Kremer",
        47: "Esmalte",
        48: "Lapislázuli",
        49: "Azul añil",
        50: "Resinato de cobre",
        51: "Malaquita",
        52: "Tierra verde de bohemia",
        53: "Negro marfil o de huesos",
        54: "Negro de vid francés",
    },
    'Y1': {
        58: "Gualda",
    },
    'Y3': {
        66: "Almagre",
        67: "Azarcón o minio",
        68: "Laca de cochinilla",
        69: "Laca de alizarina",
    },
    'Y4': {
        70: "Ocre de mina inglés.Kremer",
        72: "Amarillo de plomo. Lead Tin Yellow Deep. Kremer 10120",
        73: "Gualda",
        74: "Arzica",
        75: "Pardo antílope",
        76: "Sombra tostada de Chipre",
        77: "Ocre alemán oscuro",
        78: "Tierra de Siena tostada oscura",
        79: "Betún de Judea",
        80: "Cinabrio.Molida en el LDOA",
        81: "Hematita natural",
        82: "Minio",
        83: "Cochinilla",
        84: "Carmín de alizarina",
        85: "Laca rubia",
        86: "Azurita natural. Zeechi",
        87: "Esmalte",
        88: "Lapislázuli",
        89: "Añil o Índigo",
        90: "Resinato de cobre",
        91: "Malaquita natural",
        92: "Terra verde",
        93: "Negro de huesos o marfil",
        94: "Negro de vid francés",
    },
    'Y5': {
        95: "Acetato básico de cobre. Verdigris",
        96: "Malaquita africana",
        97: "Tierra verde de Verona",
        98: "Negro de huesos",
        99: "Negro de humo",
    },
    'Y6': {
        100: "Rejalgar",
        101: "Azurita",
        102: "Esmalte",
        103: "Lapislázuli",
        104: "Índigo o añil",
    },
    'Y7': {
        105: "Resinato de cobre",
        106: "Malaquita",
        107: "Tierra verde de bohemia",
        108: "Negro de huesos",
        109: "Negro de humo. Kremer",
        110: "Resinato de cobre",
        112: "Amarillo de plomo estaño. Tipo I. Kremer",
        114: "Ancorca. Zeechi",
        115: "Tierra de Sombra",
        116: "Tierra tostada de Chipre",
        117: "Siena. Kremer",
        119: "Espalto",
        121: "Almagre",
        122: "Azarcón o minio",
        123: "Cochinilla. Tlapanocheztli",
        124: "Alizarina. Zeechi",
        125: "Laca rubia. Zeechi",
        126: "Azurita. Zeechi",
        127: "Esmalte. Kremer",
        128: "Lapislázuli",
        129: "Índigo. Kremer",
        130: "Resinato de cobre, Blanco de plomo, ocre y negro de vid",
        131: "Malaquita africana",
        132: "Tierra verde de bohemia",
        133: "Negro de huesos o marfil",
        134: "Negro de vid francés",
        135: "Bermellon. Kremer",
        136: "Cochinilla. Laca carmín",
        137: "Azurita. Zeechi",
        139: "Blanco de plomo. Kremer",
    },
        'Y8': {
        140: "Bermellon. Kremer",
        141: "Cochinilla. Laca carmín",
        142: "Azurita. Zeechi",
        143: "Amarillo de plomo Lead Tin Yellow Deep. Kremer 10110",
        144: "Blanco de plomo. Kremer",
    }
}