.TH "actualizaCSV_DB" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
actualizaCSV_DB
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinsertar_lista_a_registro_espectros\fP (list espectros)"
.br
.ti -1c
.RI "\fBrecibe_csv_actualiza_db\fP (str ruta)"
.br
.ti -1c
.RI "\fBactualiza_y_entrena\fP (str ruta)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBruta\fP = str(input())"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Este modulo se encarga de actualizar la base de datos con una lista de espectro

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "actualizaCSV_DB\&.actualiza_y_entrena (str ruta)"

.PP
.nf
Método que recibe la ruta de un csv, actualiza la base de datos y entrena los modelos
@param ruta: ruta del csv

.fi
.PP
 
.PP
Definition at line \fB73\fP of file \fBactualizaCSV_DB\&.py\fP\&.
.SS "actualizaCSV_DB\&.insertar_lista_a_registro_espectros (list espectros)"

.PP
.nf
    Método que recibe una lista de espectros y los inserta en la base de datos
    @param espectros: lista de espectros     

.fi
.PP
 
.PP
Definition at line \fB13\fP of file \fBactualizaCSV_DB\&.py\fP\&.
.SS "actualizaCSV_DB\&.recibe_csv_actualiza_db (str ruta)"

.PP
.nf
Método que recibe la ruta de un csv y actualiza la base de datos
@param ruta: ruta del csv

.fi
.PP
 
.PP
Definition at line \fB49\fP of file \fBactualizaCSV_DB\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "actualizaCSV_DB\&.ruta = str(input())"

.PP
Definition at line \fB84\fP of file \fBactualizaCSV_DB\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
