.TH "clasificador.Hilo" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clasificador.Hilo
.SH SYNOPSIS
.br
.PP
.PP
Inherits QThread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self, nombreArchivo)"
.br
.ti -1c
.RI "\fBrun\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBnombreArchivo\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBenviarTexto\fP = pyqtSignal(str)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Clase que lee el archivo
@param QThread: Clase de la libreria PyQt5

.fi
.PP
 
.PP
Definition at line \fB175\fP of file \fBclasificador\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "clasificador\&.Hilo\&.__init__ ( self,  nombreArchivo)"

.PP
.nf
Constructor de la clase
@param self: instancia de la clase
@param nombreArchivo: nombre del archivo a leer

.fi
.PP
 
.PP
Definition at line \fB182\fP of file \fBclasificador\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "clasificador\&.Hilo\&.run ( self)"

.PP
.nf
Método que lee el archivo y envia el texto al hilo principal

.fi
.PP
 
.PP
Definition at line \fB191\fP of file \fBclasificador\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "clasificador\&.Hilo\&.enviarTexto = pyqtSignal(str)\fR [static]\fP"

.PP
Definition at line \fB180\fP of file \fBclasificador\&.py\fP\&.
.SS "clasificador\&.Hilo\&.nombreArchivo"

.PP
Definition at line \fB189\fP of file \fBclasificador\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
