.TH "controlSpec" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
controlSpec
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBobten_spec\fP (carpeta, tabla, espectro)"
.br
.ti -1c
.RI "\fBimprimir_spec\fP (carpeta, tabla, espectro)"
.br
.ti -1c
.RI "\fBget_df\fP (carpeta, tabla, espectro)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Este módulo se encarga de controlar la busqueda de espectros

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "controlSpec\&.get_df ( carpeta,  tabla,  espectro)"

.PP
.nf
Método encargado de obtener el espectro de la carpeta y tabla especificada
    @args:
        carpeta: carpeta donde se encuentra el espectro
        tabla: tabla donde se encuentra el espectro
        espectro: nombre del espectro
    @returns:
        Dataframe con el espectro

.fi
.PP
 
.PP
Definition at line \fB49\fP of file \fBcontrolSpec\&.py\fP\&.
.SS "controlSpec\&.imprimir_spec ( carpeta,  tabla,  espectro)"

.PP
.nf
Método encargado de imprimir el espectro de la carpeta y tabla especificada
@args:
    carpeta: carpeta donde se encuentra el espectro
    tabla: tabla donde se encuentra el espectro
    espectro: nombre del espectro

.fi
.PP
 
.PP
Definition at line \fB33\fP of file \fBcontrolSpec\&.py\fP\&.
.SS "controlSpec\&.obten_spec ( carpeta,  tabla,  espectro)"

.PP
.nf
Método encargado de obtener el espectro de la carpeta y tabla especificada
@args:
    carpeta: carpeta donde se encuentra el espectro
    tabla: tabla donde se encuentra el espectro
    espectro: nombre del espectro
@returns:
    Ruta del espectro

.fi
.PP
 
.PP
Definition at line \fB12\fP of file \fBcontrolSpec\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
