.TH "control_entrenador" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
control_entrenador
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_x_y\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBrecupera_ejemplares\fP ()"
.br
.ti -1c
.RI "\fBrecupera_espectros\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Modulo encargado de recuperar los ejemplares de la base de datos

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "control_entrenador\&.get_x_y ( ejemplares,  etiqueta_a_usar)"

.PP
Definition at line \fB31\fP of file \fBcontrol_entrenador\&.py\fP\&.
.SS "control_entrenador\&.recupera_ejemplares ()"

.PP
Definition at line \fB48\fP of file \fBcontrol_entrenador\&.py\fP\&.
.SS "control_entrenador\&.recupera_espectros ()"

.PP
Definition at line \fB71\fP of file \fBcontrol_entrenador\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
