.TH "entrenadorReduccion" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entrenadorReduccion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhaz_pca_regresion_logistica\fP (X, y, int componentes, etiqueta_a_usar)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBetiqueta_a_usar\fP = 'pigmento'"
.br
.ti -1c
.RI "\fBejemplares\fP = recupera_espectros()"
.br
.ti -1c
.RI "\fBno_ejem\fP = len(ejemplares)"
.br
.ti -1c
.RI "int \fBmax_accuracy\fP = 0"
.br
.ti -1c
.RI "int \fBmax_componentes\fP = 0"
.br
.ti -1c
.RI "\fBX\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.ti -1c
.RI "\fBmodel\fP"
.br
.ti -1c
.RI "\fBaccuracy\fP"
.br
.ti -1c
.RI "\fBstep\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Modulo encargado de realizar la reducción de dimensionalidad y la regresión logística\&.
Sin embargo, no se usa en el entrenamiento

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "entrenadorReduccion\&.haz_pca_regresion_logistica ( X,  y, int componentes,  etiqueta_a_usar)"

.PP
.nf
Método encargado de realizar la reducción de dimensionalidad y la regresión logística
    @args:
        X: ejemplares a usar
        y: etiqueta a usar
        componentes: número de componentes
        etiqueta_a_usar: etiqueta que se usará para guardar el modelo
    @returns:
        modelo y precisión

.fi
.PP
 
.PP
Definition at line \fB12\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "entrenadorReduccion\&.accuracy"

.PP
Definition at line \fB58\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.ejemplares = recupera_espectros()"

.PP
Definition at line \fB47\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "str entrenadorReduccion\&.etiqueta_a_usar = 'pigmento'"

.PP
Definition at line \fB45\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "int entrenadorReduccion\&.max_accuracy = 0"

.PP
Definition at line \fB52\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "int entrenadorReduccion\&.max_componentes = 0"

.PP
Definition at line \fB54\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.model"

.PP
Definition at line \fB58\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.no_ejem = len(ejemplares)"

.PP
Definition at line \fB49\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.step"

.PP
Definition at line \fB77\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.X"

.PP
Definition at line \fB57\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SS "entrenadorReduccion\&.y"

.PP
Definition at line \fB57\fP of file \fBentrenadorReduccion\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
