.TH "entrenador" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entrenador
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBguardar_modelo\fP (modelo, nombre, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_GNB\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_linear_regression\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_logistic_Regression\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_perceptron\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_random_forest\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBget_svc\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBaplicar_PCA\fP (X, y)"
.br
.ti -1c
.RI "\fBhaz_pca_regresion_logistica\fP (ejemplares, etiqueta_a_usar)"
.br
.ti -1c
.RI "\fBrealizar_entrenamiento\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "str \fBGUARDANDO_MODELO_MSG\fP = 'Guardando el modelo'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Este módulo se encarga de entrenar los modelos de clasificación y regresión

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "entrenador\&.aplicar_PCA ( X,  y)"

.PP
.nf
Método encargado de aplicar PCA\&. Sin embargo, no se usa en el entrenamiento
@args:
    X: ejemplares a usar
    y: etiqueta a usar

.fi
.PP
 
.PP
Definition at line \fB206\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_GNB ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de obtener el modelo de Naive Bayes
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB42\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_linear_regression ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de obtener el modelo de regresión lineal
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB68\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_logistic_Regression ( ejemplares,  etiqueta_a_usar)"

.PP
Definition at line \fB102\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_perceptron ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de obtener el modelo de perceptrón
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo        

.fi
.PP
 
.PP
Definition at line \fB123\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_random_forest ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de obtener el modelo de Random Forest
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB150\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.get_svc ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de obtener el modelo de SVM Support Vector Machine
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB180\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.guardar_modelo ( modelo,  nombre,  etiqueta_a_usar)"

.PP
.nf
Método encargado de guardar el modelo
@args:
    modelo: modelo a guardar
    nombre: nombre del modelo
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB28\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.haz_pca_regresion_logistica ( ejemplares,  etiqueta_a_usar)"

.PP
.nf
Método encargado de aplicar PCA y obtener el modelo de regresión logística
@args:
    ejemplares: ejemplares a usar
    etiqueta_a_usar: etiqueta que se usará para guardar el modelo

.fi
.PP
 
.PP
Definition at line \fB220\fP of file \fBentrenador\&.py\fP\&.
.SS "entrenador\&.realizar_entrenamiento ()"

.PP
.nf
Método encargado de realizar el entrenamiento de los modelos: Perceptron, Naive Bayes, Linear Regression, Logistic Regression, Random Forest, SVM

.fi
.PP
 
.PP
Definition at line \fB248\fP of file \fBentrenador\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "str entrenador\&.GUARDANDO_MODELO_MSG = 'Guardando el modelo'"

.PP
Definition at line \fB26\fP of file \fBentrenador\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
