.TH "organizador" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
organizador
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHelloWindow\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcombinar_ventanas\fP (self, ventanas)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBapp\fP = QtWidgets\&.QApplication(sys\&.argv)"
.br
.ti -1c
.RI "\fBmain_win\fP = \fBHelloWindow\fP()"
.br
.ti -1c
.RI "\fBventana\fP"
.br
.ti -1c
.RI "\fBinfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Este modulo contiene la vista de la aplicacion, la cual permite buscar espectros en la base de datos

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "organizador\&.combinar_ventanas ( self,  ventanas)"

.PP
.nf
Método encargado de combinar las ventanas de los espectros seleccionados 
@param self: vista de la aplicacion
@param ventanas: lista de ventanas

.fi
.PP
 
.PP
Definition at line \fB181\fP of file \fBorganizador\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "organizador\&.app = QtWidgets\&.QApplication(sys\&.argv)"

.PP
Definition at line \fB277\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.info"

.PP
Definition at line \fB228\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.main_win = \fBHelloWindow\fP()"

.PP
Definition at line \fB278\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.ventana"

.PP
Definition at line \fB220\fP of file \fBorganizador\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
