.TH "organizador.HelloWindow" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
organizador.HelloWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__init__\fP (self)"
.br
.ti -1c
.RI "\fBbuscar\fP (self, scroll)"
.br
.ti -1c
.RI "\fBagregarFiltro\fP (self, llave, text)"
.br
.ti -1c
.RI "\fBseleccionar\fP (self, espectro, ventanas)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfiltros\fP"
.br
.ti -1c
.RI "\fBtextbox\fP"
.br
.ti -1c
.RI "\fBbutton\fP"
.br
.ti -1c
.RI "\fBlfiltros\fP"
.br
.ti -1c
.RI "\fBventana\fP"
.br
.ti -1c
.RI "\fBfigure\fP"
.br
.ti -1c
.RI "\fBcanvas\fP"
.br
.ti -1c
.RI "\fBax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Clase encargada de la vista de la aplicacion

.fi
.PP
 
.PP
Definition at line \fB18\fP of file \fBorganizador\&.py\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "organizador\&.HelloWindow\&.__init__ ( self)"

.PP
.nf
Método encargado de inicializar la vista de la aplicacion

.fi
.PP
 
.PP
Definition at line \fB23\fP of file \fBorganizador\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "organizador\&.HelloWindow\&.agregarFiltro ( self,  llave,  text)"

.PP
.nf
Método encargado de agregar un filtro a la lista de filtros
    @param llave: llave del filtro
    @param text: texto del filtro
    @return: lista de filtros

.fi
.PP
 
.PP
Definition at line \fB113\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.buscar ( self,  scroll)"

.PP
.nf
Método encargado de buscar el espectro en la base de datos usando el buscador
    @param scroll: scroll para mostrar los resultados

.fi
.PP
 
.PP
Definition at line \fB92\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.seleccionar ( self,  espectro,  ventanas)"

.PP
.nf
Método encargado de seleccionar el espectro y mostrarlo
@param espectro: espectro seleccionado
@param ventanas: lista de ventanas

.fi
.PP
 
.PP
Definition at line \fB123\fP of file \fBorganizador\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "organizador\&.HelloWindow\&.ax"

.PP
Definition at line \fB163\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.button"

.PP
Definition at line \fB63\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.canvas"

.PP
Definition at line \fB161\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.figure"

.PP
Definition at line \fB160\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.filtros"

.PP
Definition at line \fB29\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.lfiltros"

.PP
Definition at line \fB69\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.textbox"

.PP
Definition at line \fB60\fP of file \fBorganizador\&.py\fP\&.
.SS "organizador\&.HelloWindow\&.ventana"

.PP
Definition at line \fB131\fP of file \fBorganizador\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
