.TH "recoverRegister" 3 "Version 1" "Servicio-Social-Clasificador-Organizador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
recoverRegister
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_df_from_txt\fP (file)"
.br
.ti -1c
.RI "\fBcreate_df_from_txt\fP (file)"
.br
.ti -1c
.RI "\fBget_df_from_asd\fP (file)"
.br
.ti -1c
.RI "\fBget_df_from_ruta\fP (ruta)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Este archivo contiene las funciones para recuperar los datos de los archivos

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "recoverRegister\&.create_df_from_txt ( file)"

.PP
.nf
Este método se encarga de crear un dataframe a partir de un archivo txt
    @param file: archivo asd
    @return: DataFrame

.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBrecoverRegister\&.py\fP\&.
.SS "recoverRegister\&.get_df_from_asd ( file)"

.PP
.nf
Este método se encarga de obtener un dataframe a partir de un archivo asd
    @param file: archivo asd
    @return: DataFrame

.fi
.PP
 
.PP
Definition at line \fB32\fP of file \fBrecoverRegister\&.py\fP\&.
.SS "recoverRegister\&.get_df_from_ruta ( ruta)"

.PP
.nf
Este método se encarga de obtener un dataframe a partir de una ruta\&.
    @param ruta: ruta del archivo
    @return: DataFrame

.fi
.PP
 
.PP
Definition at line \fB48\fP of file \fBrecoverRegister\&.py\fP\&.
.SS "recoverRegister\&.get_df_from_txt ( file)"

.PP
.nf
Este método se encarga de obtener un dataframe a partir de un archivo txt 
    @param file: archivo txt
    @return: DataFrame

.fi
.PP
 
.PP
Definition at line \fB7\fP of file \fBrecoverRegister\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Servicio-Social-Clasificador-Organizador from the source code\&.
